Get-DbaUserPermissions Exclude Securables
dataplat/dbatools pull request #8149
Opened 2022-02-06 00:14 UTC by sqldeployhelmet

This commit updates the function to accept a switch to ignore
securables at the database and server level. This is useful
when a database has an excessive number of users and objects
and/or the user is simply interested in role memberships.

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (effects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Ran into an issue with a 3rd party vendor db where the full roles and db securables returned over 4 million rows and function never returned. Adding a switch to return just role memberships would be keep this function useful in this case as role memberships are the only permissions I am actually concerned with at this point.

### Approach
Added a switch to the function that excludes the second half of the server and db queries when they are not desired.

2022-02-06 10:52 UTC, andreasjordan requested changes
As this adds a new parameter, you have to also change the parameter test in tests/Get-DbaUserPermission.tests.ps1

2022-02-06 10:52 UTC, andreasjordan commented on functions/Get-DbaUserPermission.ps1
> +        if -not ($ExcludeSecurables) {
Has to be `if (-not $ExcludeSecurables) {`.

2022-02-06 10:52 UTC, andreasjordan commented on functions/Get-DbaUserPermission.ps1
> +        if -not ($ExcludeSecurables) {
Has to be `if (-not $ExcludeSecurables) {`.

2022-02-06 11:58 UTC, potatoqualitee commented
Thank you! I'll make a couple code suggestion, then you can review an accept and tests should pass 👍🏼

2022-02-06 11:59 UTC, potatoqualitee commented on functions/Get-DbaUserPermission.ps1
> +        if -not ($ExcludeSecurables) {
```suggestion
        if (-not $ExcludeSecurables) {
```

2022-02-06 12:00 UTC, potatoqualitee commented on functions/Get-DbaUserPermission.ps1
> +        if -not ($ExcludeSecurables) {
```suggestion
        if (-not $ExcludeSecurables) {
```

2022-02-06 12:06 UTC, potatoqualitee commented
I also tried to add a suggestion for the `tests\Get-DbaUserPermission.Tests.ps1` file but could not. We test for known parameters, so `ExcludeSecurables` will need to be added there as well

https://github.com/dataplat/dbatools/blob/a961a09a5c5003aa5a373ab699721030b72180a2/tests/Get-DbaUserPermission.Tests.ps1#L8

Also, for other reviewers, I know that `ExcludeSecurables` is plural and we default to singular, but in this case, securables plural qualifies as its always more than one.

Thanks again,
Chrissy

2022-02-06 16:01 UTC, wsmelton requested changes
I may be missing this but wouldn't this be easier to implement by simply adding a filter for the query?

https://github.com/dataplat/dbatools/blob/a961a09a5c5003aa5a373ab699721030b72180a2/functions/Get-DbaUserPermission.ps1#L192-L194

The filter could be added here as:

```powershell
if ($ExcludeSecurables) {$dbSql += " AND Type NOT IN ('DB SECURABLES', 'SERVER SECURABLES')}
```

2022-02-06 16:01 UTC, wsmelton commented on functions/Get-DbaUserPermission.ps1
> +        For databases with a large number of objects getting object level permissions can be undesirable. Including this
```suggestion
        Allow you to exclude object-level permissions from the output, and only return role permission(s).
```

2022-02-06 16:01 UTC, wsmelton commented on functions/Get-DbaUserPermission.ps1
> +        For databases with a large number of objects getting object level permissions can be undesirable. Including this
Simplify the definition

2022-02-06 16:08 UTC, wsmelton commented on functions/Get-DbaUserPermission.ps1
> +        Allow you to exclude object-level permissions from the output, and only return role permission(s).
```suggestion
        Allows you to exclude object-level permissions from the output, and only return role permission(s).
```

Sorry, forgot the (s).

2022-02-06 16:12 UTC, sqldeployhelmet commented
@wsmelton I agree that would be more in line with how the other switches are implemented. But I am torn because as running the second half of the union is doing work we want to simply avoid?

>The filter could be added here as:
>if ($ExcludeSecurables) {$dbSql += " AND Type NOT IN ('DB SECURABLES', 'SERVER SECURABLES')}

2022-02-06 16:32 UTC, wsmelton commented
If that is the case I would refactor the whole query order so it is more clear from code what is being excluded:

(includes reformatting to fix tabbing)

```
    begin {
        $endSQL = "BEGIN TRY DROP FUNCTION STIG.server_effective_permissions END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP VIEW STIG.server_permissions END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP FUNCTION STIG.members_of_server_role END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP FUNCTION STIG.server_roles_of END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP VIEW STIG.server_role_members END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP FUNCTION STIG.database_effective_permissions END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP VIEW STIG.database_permissions END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP FUNCTION STIG.members_of_db_role END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP FUNCTION STIG.database_roles_of END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP VIEW STIG.database_role_members END TRY BEGIN CATCH END CATCH;
        GO
        BEGIN TRY DROP SCHEMA STIG END TRY BEGIN CATCH END CATCH;
        GO"

        $serverSQL = "SELECT  'SERVER LOGINS' AS Type,
                sl.name AS Member,
                ISNULL(srm.Role, 'None') AS [Role/Securable/Class],
                ' ' AS [Schema/Owner],
                ' ' AS [Securable],
                ' ' AS [Grantee Type],
                ' ' AS [Grantee],
                ' ' AS [Permission],
                ' ' AS [State],
                ' ' AS [Grantor],
                ' ' AS [Grantor Type],
                ' ' AS [Source View]
            FROM master.sys.syslogins sl
            LEFT JOIN tempdb.[STIG].[server_role_members] srm ON sl.name = srm.Member
            WHERE sl.name NOT LIKE 'NT %' AND sl.name NOT LIKE '##%'"

        $dbSQL = "SELECT 'DB ROLE MEMBERS' AS type,
            Member,
            ISNULL(Role, 'None') AS [Role/Securable/Class],
            ' ' AS [Schema/Owner],
            ' ' AS [Securable],'
            ' ' AS [Grantee Type],
            ' ' AS [Grantee],
            ' ' AS [Permission],
            ' ' AS [State],
            ' ' AS [Grantor],
            ' ' AS [Grantor Type],
            ' ' AS [Source View]
        FROM tempdb.[STIG].[database_role_members]"

        if (-not $ExcludeSecurables) {
            $serverSQL = $serverSQL + "
                UNION
                SELECT 'SERVER SECURABLES' AS Type,
                    sl.name,
                    sp.[Securable Class] COLLATE SQL_Latin1_General_CP1_CI_AS,
                    ' ',
                    sp.[Securable],
                    sp.[Grantee Type] COLLATE SQL_Latin1_General_CP1_CI_AS,
                    sp.Grantee,'
                    sp.Permission COLLATE SQL_Latin1_General_CP1_CI_AS,'
                    sp.State COLLATE SQL_Latin1_General_CP1_CI_AS,
                    sp.Grantor,
                    sp.[Grantor Type] COLLATE SQL_Latin1_General_CP1_CI_AS,
                    sp.[Source View]
                FROM master.sys.syslogins sl
                LEFT JOIN tempdb.[STIG].[server_permissions] sp ON sl.name = sp.Grantee
                WHERE sl.name NOT LIKE 'NT %' AND sl.name NOT LIKE '##%';
                UNION
                SELECT DISTINCT 'DB SECURABLES' AS Type,
                    ISNULL(drm.member, 'None') AS [Role/Securable/Class],
                    dp.[Securable Type or Class] COLLATE SQL_Latin1_General_CP1_CI_AS,
                    dp.[Schema/Owner],
                    dp.Securable,
                    dp.[Grantee Type] COLLATE SQL_Latin1_General_CP1_CI_AS,
                    dp.Grantee,
                    dp.Permission COLLATE SQL_Latin1_General_CP1_CI_AS,
                    dp.State COLLATE SQL_Latin1_General_CP1_CI_AS,
                    dp.Grantor,
                    dp.[Grantor Type] COLLATE SQL_Latin1_General_CP1_CI_AS,
                    dp.[Source View]
                FROM tempdb.[STIG].[database_role_members] drm
                FULL JOIN tempdb.[STIG].[database_permissions] dp ON ( drm.Member = dp.Grantee OR drm.Role = dp.Grantee )
                WHERE dp.Grantor IS NOT NULL
                    AND dp.Grantee NOT IN ('public', 'guest')
                    AND [Schema/Owner] <> 'sys'"
        }

        if ($IncludePublicGuest) { $dbSQL = $dbSQL.Replace("AND dp.Grantee NOT IN ('public', 'guest')", "") }
        if ($IncludeSystemObjects) { $dbSQL = $dbSQL.Replace("AND [Schema/Owner] <> 'sys'", "") }
    }
```

2022-02-06 22:18 UTC, wsmelton reviewed
LGTM, just need to fix formatting.

You can run `Invoke-DbatoolsFormatter` against the file path for this file and it should fix it for you.

2022-02-07 07:31 UTC, andreasjordan approved these changes
Looks good to me.

2022-02-07 09:52 UTC, potatoqualitee commented
Thank you both 🙇🏼 !

2022-02-07 09:52 UTC, merged

2022-02-07 09:53 UTC, potatoqualitee commented
And thank you for your first P, @sqldeployhelmet !

2022-02-08 01:07 UTC, sqldeployhelmet commented
A big thank you from me as well!