Set-DbaDbCompression, prefer online rebuilds where possible
dataplat/dbatools pull request #9118
Opened 2023-10-08 14:22 UTC by niphlod

## Please read -- recent changes to our repo
On November 10, 2022, [we removed some bloat from our repository (for the second and final time)](https://github.com/dataplat/dbatools/issues/8542). This change requires that all contributors reclone or refork their repo.

PRs from repos that have not been recently reforked or recloned will be closed and @potatoqualitee will cherry-pick your commits and open a new PR with your changes.

 - [x] Please confirm you have the smaller repo (85MB .git directory vs 275MB or 110MB or 185MB .git directory)

## Type of Change

 - [ ] Bug fix (non-breaking change, fixes # )
 - [x] New feature (non-breaking change, adds functionality, fixes #9102 )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

### Purpose
Try to do online operations where possible. 

### Approach
There's a swanky "IsOnlineRebuildSupported" on the index property to signal if the version supports online operations. Unfortunately, it's not on the database level.
So, we loop over existing indexes, and if one is found and IsOnlineRebuildSupported is true, we set the relevant flags on the rebuild operation.
Fixes:
- there was a manual FIX due to a SMO bug for resetting tables to "None", but it seems to be fixed, so I removed the workaround from the code

Problems:
- Azure gets back false on any index, even if AFAIK every Azure instance supports online rebuilds.... so we patch SMO at the top

Possible problems:
- if you just have heaps, there's no way to detect if online operations are supported if not manually detecting versions and editions 
- technically every index can have that flag .... is there some kind of situation in which one index is rebuildable online and another isn't ? if so, even if AN index is "online rebuildable", this code fails to set it on every operation, and the check must be done on each object and reverted to a clunky "globally I should be able to do it, but I can't for this specific one"... which, in Azure-related cases, is going to be impossible as the property on each index is set to false

2023-10-08 16:06 UTC, wsmelton commented on public/Set-DbaDbCompression.ps1
> +            $isAzure = $server.DatabaseEngineType -match "Azure"
This is duplicate code, it is already part of the server object via `Connect` command

https://github.com/dataplat/dbatools/blob/73ff74e4efe569025bd4c544837ff71b790c8ed7/public/Connect-DbaInstance.ps1#L1028-L1045

2023-10-08 16:07 UTC, wsmelton commented on public/Set-DbaDbCompression.ps1
> +                        if ($index.IsOnlineRebuildSupported -or $isAzure) {
```suggestion
                        if ($index.IsOnlineRebuildSupported -or $server.IsAzure) {
```

2023-10-08 16:08 UTC, wsmelton requested changes
Initial review it looks good, just need to remove duplicated code (see comments)

2023-10-08 21:23 UTC, niphlod commented
thanks @wsmelton , fixed it.

2023-10-10 15:39 UTC, potatoqualitee commented
Thankyou both!

2023-10-10 15:39 UTC, merged