Add-DbaDbRoleMember - Add support for adding roles to roles
dataplat/dbatools pull request #9319
Opened 2024-04-03 20:09 UTC by andreasjordan

## Type of Change

 - [x] Bug fix (non-breaking change, fixes #9302 )
 - [ ] New feature (non-breaking change, adds functionality, fixes # )
 - [ ] Breaking change (affects multiple commands or functionality, fixes # )
 - [ ] Ran manual Pester test and has passed (`.\tests\manual.pester.ps1`)
 - [ ] Adding code coverage to existing functionality
 - [ ] Pester test is included
 - [ ] If new file reference added for test, has is been added to github.com/dataplat/appveyor-lab ?
 - [ ] Unit test is included
 - [ ] Documentation
 - [ ] Build system

See issue for details.

2024-04-03 20:25 UTC, andreasjordan commented
We have to change Get-DbaDbRoleMember as well. Will work on this in the next days.

2024-04-10 05:55 UTC, mattcargile commented
The code looks good. Thanks!

Would love to see `DbaServerRoleMember` cmdlets get the same treatment on the parameters. Might involve more breaking changes.

2024-04-10 06:56 UTC, andreasjordan commented
Let's first have @potatoqualitee have a look at this PR. Then we can talk about breaking changes.

2024-04-11 07:46 UTC, potatoqualitee commented
thank you for the alias! @ClaudioESSilva can you pls take a look and approve?

2024-04-11 14:42 UTC, wsmelton requested changes
Just rewording suggesting...but LGTM

2024-04-11 14:42 UTC, wsmelton commented on public/Add-DbaDbRoleMember.ps1
> +        The user(s) or role(s) to add to role(s) specified.
```suggestion
        The member(s) (user or role) to add to the Roles specified.
```

2024-04-12 10:50 UTC, potatoqualitee commented
oh, good. thanks everyone 😊

2024-04-12 10:50 UTC, merged